### PR TITLE
shrekshao: add achi to the list

### PR DESCRIPTION
**Pull request by shrekshao**

### CODE REVIEW

**Comment by zentner-kyle** [comment]
Wow, that was fast. I see you also added achi.xml. I forgot to mention that in the assignment. I think I'll go change that now.

**Comment by zentner-kyle** [comment]
Could you also post achi in response to the assignment? Thanks!

**Comment by shrekshao** [comment]
-_-! Sorry but what does it mean by " post achi in response to the assignment" ?

**Comment by zentner-kyle** [comment]
Oh! On piazza, I made a [post](https://piazza.com/class/gx9iegamtgo3r7?cid=174) asking everyone to do this, about 20 minutes ago.

I wanted people to do different (interesting) games, so I wanted them to post in response to that assignment so they wouldn't all do the same game.

Anyways, I don't think everyone will pick the same game, so that part's not very important.

**Comment by zentner-kyle** [comment]
Merged in the description.

**Pull request closed without merging**
